# Generated by Django 2.1.2 on 2018-11-03 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.AccountType')),
                ('connections', models.ManyToManyField(blank=True, related_name='_profile_connections_+', to='portal.Profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=5096)),
                ('answer', models.CharField(max_length=5096)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheets',
            fields=[
                ('worksheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('O', 'Overdue'), ('C', 'Completed')], default='A', max_length=1)),
                ('profile_assigned', models.ManyToManyField(to='portal.Profile')),
                ('questions', models.ManyToManyField(to='portal.Questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.QuestionType'),
        ),
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Topics'),
        ),
        migrations.AddField(
            model_name='notes',
            name='profile_assigned',
            field=models.ManyToManyField(to='portal.Profile'),
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subjects'),
        ),
        migrations.AddField(
            model_name='notes',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Topics'),
        ),
    ]
