# Generated by Django 2.1.2 on 2018-11-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20181028_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_assigned', models.ManyToManyField(to='portal.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=5096)),
                ('answer', models.CharField(max_length=5096)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheets',
            fields=[
                ('worksheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('O', 'Overdue'), ('C', 'Completed')], default='A', max_length=1)),
                ('profile_assigned', models.ManyToManyField(to='portal.Profile')),
                ('questions', models.ManyToManyField(to='portal.Questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.QuestionType'),
        ),
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Topics'),
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subjects'),
        ),
        migrations.AddField(
            model_name='notes',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Topics'),
        ),
    ]
