# Generated by Django 2.1.2 on 2018-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20181103_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='_profile_connections_+', to='portal.Profile'),
        ),
    ]
