# Generated by Django 2.1.2 on 2018-11-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_worksheet_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Subject'),
        ),
    ]
