# Generated by Django 2.1.2 on 2018-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_worksheet_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile_assigned',
            field=models.ManyToManyField(blank=True, null=True, to='portal.Profile'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='portal.Question'),
        ),
    ]
