# Generated by Django 2.1.2 on 2018-11-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20181103_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('A', 'Assigned'), ('O', 'Overdue'), ('C', 'Completed')], default='U', max_length=1),
        ),
    ]
