# Generated by Django 2.1.2 on 2018-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20181105_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='enquiries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='persontype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
