# Generated by Django 2.1.2 on 2018-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20181105_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('persontype', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('enquiries', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='age',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='enquiries',
        ),
    ]
