# Generated by Django 2.1.2 on 2018-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20181105_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='persontype',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='number',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
