# Generated by Django 2.1.2 on 2018-11-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20181106_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
