# Generated by Django 2.1.2 on 2018-12-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recommend', models.EmailField(blank=True, max_length=254, null=True)),
                ('mostimportant', models.EmailField(blank=True, max_length=254, null=True)),
                ('useability', models.IntegerField(blank=True, null=True)),
                ('content', models.IntegerField(blank=True, null=True)),
                ('impact', models.IntegerField(blank=True, null=True)),
                ('aesthetics', models.IntegerField(blank=True, null=True)),
                ('scope', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
